name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: jpetrucciani/mypy-check@0.971
      with:
        path: shyster
    - uses: fastai/workflows/nbdev-ci@master
